# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LocationFinder
                                 A QGIS plugin
 QGIS Client for LocationFinder (interactive geocoding)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-26
        copyright            : (C) 2023 by ujr for Dira GeoSystems
        email                : ujr@dirageosystems.ch
        git sha              : $Format:%H$
        license              : MIT License
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LocationFinder class from file LocationFinder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .location_finder import LocationFinderPlugin
    return LocationFinderPlugin(iface)
